---
schema:
    - ['id','TEXT']
    - ['first_name','TEXT']
    - ['last_name','TEXT']
    - ['state','TEXT']
    - ['district','TEXT']
    - ['party','TEXT']
    - ['birthday','TEXT']
    - ['birth_year','INTEGER']
    - ['birth_quarter','INTEGER']
    - ['birth_month','INTEGER']
    - ['url','TEXT']
    - ['twitter','TEXT']
    - ['facebook','TEXT']
    - ['facebook_id','TEXT']
    - ['youtube','TEXT']
    - ['youtube_id','TEXT']
    - ['opensecrets_id','TEXT']
    - ['wikipedia_id','TEXT']
    - ['washington_post_id','TEXT']
keys:
    - id
...
